[2024-12-04T23:41:26.036+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: etl_tmdb_us_movies.extract_tmdb_movies_last_month manual__2024-12-04T23:39:11.416386+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
