[2024-12-05T06:15:10.114+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-05T06:15:10.140+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_elt_process.dbt_run manual__2024-12-05T06:15:09.600333+00:00 [queued]>
[2024-12-05T06:15:10.144+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_elt_process.dbt_run manual__2024-12-05T06:15:09.600333+00:00 [queued]>
[2024-12-05T06:15:10.144+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-12-05T06:15:10.149+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run> on 2024-12-05 06:15:09.600333+00:00
[2024-12-05T06:15:10.153+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_elt_process', 'dbt_run', 'manual__2024-12-05T06:15:09.600333+00:00', '--job-id', '843', '--raw', '--subdir', 'DAGS_FOLDER/dbt_elt_process.py', '--cfg-path', '/tmp/tmpe16lc68k']
[2024-12-05T06:15:10.158+0000] {standard_task_runner.py:91} INFO - Job 843: Subtask dbt_run
[2024-12-05T06:15:10.158+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=96258) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-05T06:15:10.159+0000] {standard_task_runner.py:63} INFO - Started process 96259 to run task
[2024-12-05T06:15:10.190+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_elt_process.dbt_run manual__2024-12-05T06:15:09.600333+00:00 [running]> on host bbf2723bdd9c
[2024-12-05T06:15:10.235+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_elt_process' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2024-12-05T06:15:09.600333+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-05T06:15:09.600333+00:00'
[2024-12-05T06:15:10.236+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-05T06:15:10.247+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-12-05T06:15:10.248+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt run --profiles-dir /opt/***/dbt_movie --project-dir /opt/***/dbt_movie']
[2024-12-05T06:15:10.252+0000] {subprocess.py:86} INFO - Output:
[2024-12-05T06:15:11.188+0000] {subprocess.py:93} INFO - Usage: dbt run [OPTIONS]
[2024-12-05T06:15:11.189+0000] {subprocess.py:93} INFO - Try 'dbt run -h' for help.
[2024-12-05T06:15:11.189+0000] {subprocess.py:93} INFO - 
[2024-12-05T06:15:11.189+0000] {subprocess.py:93} INFO - Error: Invalid value for '--profiles-dir': Path '/opt/***/dbt_movie' does not exist.
[2024-12-05T06:15:11.266+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-12-05T06:15:11.267+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-05T06:15:11.272+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-12-05T06:15:11.277+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_elt_process, task_id=dbt_run, run_id=manual__2024-12-05T06:15:09.600333+00:00, execution_date=20241205T061509, start_date=20241205T061510, end_date=20241205T061511
[2024-12-05T06:15:11.284+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 843 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 96259)
[2024-12-05T06:15:11.330+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-12-05T06:15:11.340+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-05T06:15:11.342+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
