[2024-12-04T22:48:38.475+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: etl_tmdb_us_movies.extract_tmdb_currently_playing manual__2024-12-04T22:48:34.891345+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
