[2024-12-05T07:00:38.264+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-05T07:00:38.288+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_elt_process.dbt_run manual__2024-12-05T06:19:46.869551+00:00 [queued]>
[2024-12-05T07:00:38.291+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_elt_process.dbt_run manual__2024-12-05T06:19:46.869551+00:00 [queued]>
[2024-12-05T07:00:38.291+0000] {taskinstance.py:2306} INFO - Starting attempt 5 of 5
[2024-12-05T07:00:38.296+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run> on 2024-12-05 06:19:46.869551+00:00
[2024-12-05T07:00:38.301+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_elt_process', 'dbt_run', 'manual__2024-12-05T06:19:46.869551+00:00', '--job-id', '850', '--raw', '--subdir', 'DAGS_FOLDER/dbt_elt_process.py', '--cfg-path', '/tmp/tmp8jfiqmmf']
[2024-12-05T07:00:38.308+0000] {standard_task_runner.py:91} INFO - Job 850: Subtask dbt_run
[2024-12-05T07:00:38.308+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=98620) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-05T07:00:38.310+0000] {standard_task_runner.py:63} INFO - Started process 98621 to run task
[2024-12-05T07:00:38.340+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_elt_process.dbt_run manual__2024-12-05T06:19:46.869551+00:00 [running]> on host bbf2723bdd9c
[2024-12-05T07:00:38.384+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_elt_process' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2024-12-05T06:19:46.869551+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-05T06:19:46.869551+00:00'
[2024-12-05T07:00:38.384+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-05T07:00:38.394+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-12-05T07:00:38.395+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt run --profiles-dir /opt/***/dbt_movie/ --project-dir /opt/***/dbt_movie/']
[2024-12-05T07:00:38.398+0000] {subprocess.py:86} INFO - Output:
[2024-12-05T07:00:39.337+0000] {subprocess.py:93} INFO - Usage: dbt run [OPTIONS]
[2024-12-05T07:00:39.338+0000] {subprocess.py:93} INFO - Try 'dbt run -h' for help.
[2024-12-05T07:00:39.338+0000] {subprocess.py:93} INFO - 
[2024-12-05T07:00:39.338+0000] {subprocess.py:93} INFO - Error: Invalid value for '--profiles-dir': Path '/opt/***/dbt_movie/' does not exist.
[2024-12-05T07:00:39.421+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-12-05T07:00:39.422+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-05T07:00:39.429+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-12-05T07:00:39.436+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_elt_process, task_id=dbt_run, run_id=manual__2024-12-05T06:19:46.869551+00:00, execution_date=20241205T061946, start_date=20241205T070038, end_date=20241205T070039
[2024-12-05T07:00:39.448+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 850 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 98621)
[2024-12-05T07:00:39.468+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-12-05T07:00:39.530+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-05T07:00:39.543+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
