[2024-12-04T23:04:24.050+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-04T23:04:24.068+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_tmdb_us_movies.load_tmdb_data_to_snowflake scheduled__2024-12-04T22:00:00+00:00 [queued]>
[2024-12-04T23:04:24.073+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_tmdb_us_movies.load_tmdb_data_to_snowflake scheduled__2024-12-04T22:00:00+00:00 [queued]>
[2024-12-04T23:04:24.074+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-12-04T23:04:24.079+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_tmdb_data_to_snowflake> on 2024-12-04 22:00:00+00:00
[2024-12-04T23:04:24.091+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=75251) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-04T23:04:24.093+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_tmdb_us_movies', 'load_tmdb_data_to_snowflake', 'scheduled__2024-12-04T22:00:00+00:00', '--job-id', '795', '--raw', '--subdir', 'DAGS_FOLDER/tmdb_historical.py', '--cfg-path', '/tmp/tmpfndguye2']
[2024-12-04T23:04:24.095+0000] {standard_task_runner.py:91} INFO - Job 795: Subtask load_tmdb_data_to_snowflake
[2024-12-04T23:04:24.095+0000] {standard_task_runner.py:63} INFO - Started process 75261 to run task
[2024-12-04T23:04:24.136+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_tmdb_us_movies.load_tmdb_data_to_snowflake scheduled__2024-12-04T22:00:00+00:00 [running]> on host bbf2723bdd9c
[2024-12-04T23:04:24.204+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_tmdb_us_movies' AIRFLOW_CTX_TASK_ID='load_tmdb_data_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2024-12-04T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-04T22:00:00+00:00'
[2024-12-04T23:04:24.205+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-04T23:04:24.218+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-12-04T23:04:24.218+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.0, Python Version: 3.12.3, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2024-12-04T23:04:24.219+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-12-04T23:04:24.954+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-12-04T23:04:24.955+0000] {logging_mixin.py:188} INFO - Transaction rolled back due to error: 'SnowflakeConnection' object has no attribute 'begin'
[2024-12-04T23:04:24.955+0000] {connection.py:762} INFO - closed
[2024-12-04T23:04:25.019+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-12-04T23:04:25.163+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-12-04T23:04:25.166+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-04T23:04:25.202+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_tmdb_us_movies, task_id=load_tmdb_data_to_snowflake, run_id=scheduled__2024-12-04T22:00:00+00:00, execution_date=20241204T220000, start_date=20241204T230424, end_date=20241204T230425
[2024-12-04T23:04:25.278+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-12-04T23:04:25.363+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-04T23:04:25.367+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-12-04T23:40:30.430+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-04T23:40:30.446+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_tmdb_us_movies.load_tmdb_data_to_snowflake scheduled__2024-12-04T22:00:00+00:00 [queued]>
[2024-12-04T23:40:30.451+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_tmdb_us_movies.load_tmdb_data_to_snowflake scheduled__2024-12-04T22:00:00+00:00 [queued]>
[2024-12-04T23:40:30.451+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-12-04T23:40:30.457+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_tmdb_data_to_snowflake> on 2024-12-04 22:00:00+00:00
[2024-12-04T23:40:30.464+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=76846) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-04T23:40:30.465+0000] {standard_task_runner.py:63} INFO - Started process 76853 to run task
[2024-12-04T23:40:30.464+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_tmdb_us_movies', 'load_tmdb_data_to_snowflake', 'scheduled__2024-12-04T22:00:00+00:00', '--job-id', '813', '--raw', '--subdir', 'DAGS_FOLDER/tmdb_historical.py', '--cfg-path', '/tmp/tmpct1u5svo']
[2024-12-04T23:40:30.472+0000] {standard_task_runner.py:91} INFO - Job 813: Subtask load_tmdb_data_to_snowflake
[2024-12-04T23:40:30.515+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_tmdb_us_movies.load_tmdb_data_to_snowflake scheduled__2024-12-04T22:00:00+00:00 [running]> on host bbf2723bdd9c
[2024-12-04T23:40:30.604+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_tmdb_us_movies' AIRFLOW_CTX_TASK_ID='load_tmdb_data_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2024-12-04T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-04T22:00:00+00:00'
[2024-12-04T23:40:30.605+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-04T23:40:30.609+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-12-04T23:40:30.610+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.0, Python Version: 3.12.3, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2024-12-04T23:40:30.611+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-12-04T23:40:31.155+0000] {logging_mixin.py:188} INFO - Starting transaction...
[2024-12-04T23:40:31.334+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-12-04T23:40:31.859+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-12-04T23:41:26.431+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2024-12-04T23:41:26.436+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-12-04T23:41:26.437+0000] {process_utils.py:132} INFO - Sending 15 to group 76853. PIDs of all processes in the group: [76853]
[2024-12-04T23:41:26.437+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 76853
[2024-12-04T23:41:26.438+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-12-04T23:41:26.442+0000] {connection.py:762} INFO - closed
[2024-12-04T23:41:26.714+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-12-04T23:41:26.802+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-04T23:41:26.830+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tmdb_historical.py", line 183, in load_tmdb_data_to_snowflake
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 977, in execute
    ret = self._execute_helper(query, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 694, in _execute_helper
    ret = self._connection.cmd_query(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/connection.py", line 1309, in cmd_query
    ret = self.rest.request(
          ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/network.py", line 493, in request
    return self._post_request(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/network.py", line 734, in _post_request
    ret = self.fetch(
          ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/network.py", line 843, in fetch
    ret = self._request_exec_wrapper(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/network.py", line 884, in _request_exec_wrapper
    return_object = self._request_exec(
                    ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/network.py", line 1078, in _request_exec
    raw_ret = session.request(
              ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 467, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 462, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 707, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/contrib/pyopenssl.py", line 330, in recv_into
    if not util.wait_for_read(self.socket, self.socket.gettimeout()):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/util/wait.py", line 145, in wait_for_read
    return wait_for_socket(sock, read=True, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/util/wait.py", line 106, in poll_wait_for_socket
    return bool(_retry_on_intr(do_poll, timeout))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/util/wait.py", line 43, in _retry_on_intr
    return fn(timeout)
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/util/wait.py", line 104, in do_poll
    return poll_obj.poll(t)
           ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-12-04T23:41:26.848+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_tmdb_us_movies, task_id=load_tmdb_data_to_snowflake, run_id=scheduled__2024-12-04T22:00:00+00:00, execution_date=20241204T220000, start_date=20241204T234030, end_date=20241204T234126
[2024-12-04T23:41:26.919+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=76853, status='terminated', exitcode=2, started='23:40:30') (76853) terminated with exit code 2
